### ISSUE TITLE
How to detect a press on the video?

### ISSUE THREAD

**Issue by lra-tapptic** [inProgress-team/react-native-youtube#195]
So I have the player with no controlers, autoplaying. I just want to detect when the user press the video in order to open another screen. 

So for iOS, I had to put a transparent view with position: absolute on top of the video that can be wrapper in a TouchableWithoutOpacity e.g. That also prevent the play/pause behaviour when the user tap the video (even with no controls)

But for Android, I cannot use that overlay because of the infamous UNAUTHORIZED_OVERLAY error. Wrapping the video in a TouchableWithoutOpacity doesn't work either. So is there a way to get that onPress callback ?

**Comment by davidohayon669** [comment]
@lra-tapptic I guess it can be done in the native code.. I'll have to look at it

**Comment by davidohayon669** [comment]
@lra-tapptic Looked at it and I'm afraid it's impossible to implement with the way we use this module with a [YouTubePlayerFragment](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerFragment) instead of [YouTubePlayerView](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerView) that can probably register an `onClick` listener. We use the fragment because it is much simpler for this component's use.

Anyway, I guess the best thing for someone who wants to have the amount of control that the iOS version provide, would be to implement the Android version with a WebView. I might do it someday when I'll have enough time.

**Comment by moshebeeri** [comment]
I use TouchableOpacity component

`                
     <TouchableOpacity width={this.state.width}  height={this.state.height}
                  onPress={this.onPress.bind(this)}>
                            <YouTube
                                videoId={this.state.videoId}
                                play={!this.state.paused}/>
     <TouchableOpacity/>
`

and 

`    onPress() {
            this.setState({paused: !this.state.paused});
      }
`
