### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-youtube'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by Rananjaya** [inProgress-team/react-native-youtube#302]
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-youtube'. Minimum required is 25.0.0

**Comment by ivan-abreu** [comment]
I had this very same problem and I solved it adding the lines below in  the file app/android/build.gradle

`subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion '27.0.2'
            }
        }
    }
}`

**Comment by haneefkt** [comment]
I have the same problem, tried to solve with ivan-abreu's solution. Even though the debug build is succeeded, a release build produces following error: -
---------
/appfolder/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/VideoFragment.java:6: Error: This fragment should provide a default constructor (a public constructor with no arguments) (com.inprogress.reactnativeyoutube.VideoFragment) [ValidFragment]
public class VideoFragment extends YouTubePlayerFragment {
             ~~~~~~~~~~~~~
/appfolder/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/VideoFragment.java:10: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public VideoFragment(YouTubeView youTubeView) {
           ~~~~~~~~~~~~~

   Explanation for issues of type "ValidFragment":
   From the Fragment documentation:
   Every fragment must have an empty constructor, so it can be instantiated
   when restoring its activity's state. It is strongly recommended that
   subclasses do not have other constructors with parameters, since these
   constructors will not be called when the fragment is re-instantiated;
   instead, arguments can be supplied by the caller with setArguments(Bundle)
   and later retrieved by the Fragment with getArguments().

   http://developer.android.com/reference/android/app/Fragment.html#Fragment()

2 errors, 0 warnings
:app:lintVitalRelease FAILED

FAILURE: Build failed with an exception.

**Comment by davidohayon669** [comment]
#370
