### ISSUE TITLE
Volume issues when phone on vibrate mode

### ISSUE THREAD

**Issue by adrianha** [inProgress-team/react-native-youtube#31]
Hello, I'm facing a problem when my phone is on vibrate mode then the youtube component doesnt make sound though i raised the volume up, the sound was going up when i change to normal mode. But when i used official youtube application on vibrate mode its still produce sound. How to fix this?
Thanks

**Comment by Mokto** [comment]
+1

**Comment by paramaggarwal** [comment]
The official player uses a fully custom player as far as I know, which the HTML5 player in the webview that this uses goes via iOS's APIs which will by default mute. This is standard behaviour across system and you should try to stick to it. It makes sense for the YouTube app because its primary purpose is playing views itself.

If you'd still like to override this behaviour, you could possibly expose https://github.com/0xced/XCDYouTubeKit to React Native.

**Comment by Mokto** [comment]
Closing this as I added HOW-TO in readme.
