### ISSUE TITLE
Get current time in millisecond (Android)

### ISSUE THREAD

**Issue by bmike712** [inProgress-team/react-native-youtube#365]
currentTime() method in Android returns result in second.
Is there any way to get current time in milliseconds(immediately) ?

**Comment by sblondell** [comment]
I'm not positive on how to do it with react-native-youtube because this repo didn't build for me. I had to use react-native-youtube-sdk.
For that repo, I went to "C:\<project_dir>\node_modules\react-native-youtube-sdk\example\lib
and in the file 'YouTubePlayer.js' I edited line 48
from...
".then(currentTime => resolve(Math.round(currentTime)))"
to...
".then(currentTime => resolve(currentTime))"

I hope this helps.

**Comment by davidohayon669** [comment]
@bmike712 why not multiply by 1000?
