### ISSUE TITLE
Never Ready

### ISSUE THREAD

**Issue by timscott** [inProgress-team/react-native-youtube#43]
I followed the installation instructions exactly, and used took ```index.ios.js``` from the [example](https://github.com/paramaggarwal/react-native-youtube/blob/master/Example/index.ios.js). When I run the app everything renders, but ```onReady``` never fires. I'm using react-native 0.21.0. How can I troubleshoot this?

**Comment by paramaggarwal** [comment]
Could you check by adding a breakpoint in this function here: [RCTYouTube.m#L102-L113](https://github.com/paramaggarwal/react-native-youtube/blob/master/RCTYouTube.m#L102-L113)

If the breakpoint is called, the issue is that RN is not able to deliver the event to JS.
If the breakpoint is not called, the issue is somewhere in the Youtube webview not calling delegate methods.

**Comment by timscott** [comment]
I checked that. The breakpoint was not called.

**Comment by RomanKomar** [comment]
The same problem

**Comment by smlee** [comment]
I have the same issue. I also get "Native component for myProjectName does not exist" warning.

**Comment by Mokto** [comment]
Hi guys,

onReady is called in my case.

I added this `onReady={()=>{console.warn('READY');}}` in my YouTube tag and it is called ;)

RN 0.25.1 and react-native-youtube 0.7.1

**Comment by ashleyw** [comment]
Was this fixed? Downgraded to react-native 0.38, using react-native-youtube 0.8.0.

Video plays and `seekTo()` works, however `onReady`, `onChangeState` and `onChangeQuality` are never called.

**Comment by TheIndianRaj** [comment]
Was this fixed?

**Comment by krish512** [comment]
Is this fixed yet?
